services:
  redis:
    image: redis:alpine
    container_name: apis-redis
    networks:
      - backend
    ports:
      - "6380:6379"

  app:
    build:
      context: .
    container_name: apis-app
    networks:
      - backend
    ports:
      - "3002:3002"
      - "3008:3008"
    depends_on:
      - redis

networks:
  backend:
    driver: bridge
